<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>lanwatch-server</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LanWatch.Shared\LanWatch.Shared.csproj" />
    <ProjectReference Include="..\LanWatch.Client\LanWatch.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LanWatch.Tests" />
  </ItemGroup>
</Project>
