// <auto-generated />
using LanWatch.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanWatch.Server.Data.Migrations
{
    [DbContext(typeof(LanWatchDb))]
    [Migration("20261006193551_ExceptionSignOffs")]
    partial class ExceptionSignOffs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("LanWatch.Server.Data.Client", b =>
                {
                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenUnix")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Ip");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("LanWatch.Server.Data.DownloadSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("HitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUnix")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MissBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Requests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartUnix")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastUnix");

                    b.HasIndex("Service", "ContentId");

                    b.HasIndex("ClientIp", "Service", "ContentId", "StartUnix")
                        .IsUnique();

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("LanWatch.Server.Data.ErrorEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Unix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Upstream")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Unix");

                    b.HasIndex("Kind", "Unix");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("LanWatch.Server.Data.ExceptionSignOff", b =>
                {
                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Domain")
                        .HasColumnType("TEXT");

                    b.Property<long>("SignedOffUnix")
                        .HasColumnType("INTEGER");

                    b.HasKey("Kind", "Domain");

                    b.ToTable("ExceptionSignOffs");
                });

            modelBuilder.Entity("LanWatch.Server.Data.IngestCursor", b =>
                {
                    b.Property<string>("File")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUnix")
                        .HasColumnType("INTEGER");

                    b.HasKey("File");

                    b.ToTable("IngestCursors");
                });

            modelBuilder.Entity("LanWatch.Server.Data.LanEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndUnix")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartUnix")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartUnix");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LanWatch.Server.Data.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("LanWatch.Server.Data.StatusMinute", b =>
                {
                    b.Property<long>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Minute", "Service", "Status");

                    b.ToTable("StatusMinutes");
                });

            modelBuilder.Entity("LanWatch.Server.Data.SteamDepot", b =>
                {
                    b.Property<long>("DepotId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepotId");

                    b.ToTable("SteamDepots");
                });

            modelBuilder.Entity("LanWatch.Server.Data.StreamMinute", b =>
                {
                    b.Property<long>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SniHost")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesSent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Connections")
                        .HasColumnType("INTEGER");

                    b.HasKey("Minute", "ClientIp", "SniHost", "Status");

                    b.ToTable("StreamMinutes");
                });

            modelBuilder.Entity("LanWatch.Server.Data.TrafficMinute", b =>
                {
                    b.Property<long>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .HasColumnType("TEXT");

                    b.Property<long>("ErrorRequests")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HitRequests")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MissBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MissRequests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Minute", "ClientIp", "Service");

                    b.HasIndex("ClientIp", "Minute");

                    b.ToTable("TrafficMinutes");
                });
#pragma warning restore 612, 618
        }
    }
}
